name: nodered-config

services:
  nodered:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodered-opt:local
    container_name: nodered
    restart: unless-stopped
    env_file:
      - ./runtime/.env
    ports:
      - "1880:1880"
    volumes:
      - ./runtime/config:/data:rw
      - ./runtime/data/node_modules:/data/node_modules:rw
      - ./runtime/data/public:/data/public:rw
      - ./runtime/data/package.json:/data/package.json:rw
      - ./runtime/data/package-lock.json:/data/package-lock.json:rw
      - ./runtime/data/temp:/data/temp:rw
      - ./runtime/data/databases:/data/databases:rw
      - ./runtime/data/.npm:/data/.npm:rw
      - ./runtime/logs:/logs:rw
      - /mnt/SERVER06:/mnt/SERVER06:rw
      - /mnt/PLATERANFS1:/mnt/PLATERANFS1:rw
      - /mnt/TELEFONICA:/mnt/TELEFONICA:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
